import timeit

TIMES = 10000


def clock(cmd):
    res = timeit.repeat(cmd, number=TIMES)
    return min('{:.3f}'.format(x) for x in res)


min1 = clock("print('pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab' + ':' + 'pythontab')")
min2 = clock("print(':'.join(['pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab',]))")
min3 = clock("print('pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab','pythontab', sep=':')")

print(min1)
print(min2)
print(min3)
